apiVersion: v1
kind: Service
metadata:
  name: minecraftmanager-lb
spec:
  selector:
    app: minecraftmanager
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name: portone
  type: LoadBalancer