apiVersion: v1
kind: Service
metadata:
  name: minecraft-lb-1-13-1
spec:
  selector:
    app: minecraft-1-13-1
  ports:
  - protocol: TCP
    port: 25575
    targetPort: 25575
    name: portone
  - protocol: TCP
    port: 25565
    targetPort: 25565
    name: porttwo
  type: LoadBalancer