FROM continuumio/miniconda3

RUN apt-get update -y
RUN apt-get upgrade -y

RUN apt-get install build-essential -y

RUN pip install --upgrade pip setuptools wheel

RUN conda install psutil -y

RUN apt-get install -y apt-transport-https
RUN curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
RUN echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | tee -a /etc/apt/sources.list.d/kubernetes.list
RUN apt-get update
RUN apt-get install -y kubectl

ADD requirements.txt /app/
RUN pip install -r /app/requirements.txt

EXPOSE 80

COPY . /app/

RUN mv /app/run.py /run.py

RUN chmod -x /run.py

ENV PYTHONUNBUFFERED 1

#RUN export KUBECONFIG=/secrets/kubeconfig.txt
# RUN rm ~/.kube/config
# RUN mv /secrets/kubeconfig.txt ~/.kube/config

# Turn on the Flask-DebugToolbar
ENV FLASK_DEBUG 1

CMD ["python", "/run.py"]